package com.example.car_rental_system_final.auth;

public class GoogleOAuthDesktop {
    public static String getIdToken() throws Exception {
        // Тестовый ID токен
        return "eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlOWdkazcifQ.ewogImlzcyI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLAogICJzdWIiOiAiMTIzNDU2Nzg5MCIsCiAgImF1ZCI6ICJ0ZXN0LWNsaWVudC1pZCIsCiAgImV4cCI6IDE3Mzk5OTk5OTksCiAgImlhdCI6IDE3Mzk5OTk5OTksCiAgImVtYWlsIjogInRlc3RAdGVzdC5jb20iLAogICJlbWFpbF92ZXJpZmllZCI6IHRydWUsCiAgIm5hbWUiOiAiVGVzdCBVc2VyIiwKICAicGljdHVyZSI6ICJodHRwczovL2xpbmRlbi5jb20vZGVmYXVsdC5wbmciLAogICJnaXZlbl9uYW1lIjogIlRlc3QiLAogICJmYW1pbHlfbmFtZSI6ICJVc2VyIiwKICAibG9jYWxlIjogImVuIn0.ewogICJhbGciOiAiUlMyNTYiLAogICJraWQiOiAiMWU5Z2RrNyIKfQ";
    }
} 